apiVersion: v1
kind: Template
metadata:
  name: wildfly-configmap-booster
  annotations:
    description: This templates creates a Wildlfy application using a ConfigMap for configuration.
    tags: instant-app
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: .
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
- name: ARTIFACT_DIR
  description: "Directory from which archives will be copied into the deployment folder. If unspecified, all archives in /target will be copied."
  displayName: Artifacts Directory
  value: target
  required: false
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: wildfly-configmap
    labels:
      booster: wildfly-configmap
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: runtime-wildfly-configmap
    labels:
      booster: wildfly-configmap
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: openshift/wildfly-160-centos7:latest

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: wildfly-configmap
    labels:
      booster: wildfly-configmap
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: wildfly-configmap:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime-wildfly-configmap:latest
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: ARTIFACT_DIR
          value: "${ARTIFACT_DIR}"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: wildfly-configmap
      group: io.openshift
    name: wildfly-configmap
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: wildfly-configmap
      group: io.openshift

- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: wildfly-configmap
      group: io.openshift
    name: wildfly-configmap
  spec:
    replicas: 1
    selector:
      app: wildfly-configmap
      group: io.openshift
    template:
      metadata:
        labels:
          app: wildfly-configmap
          group: io.openshift
      spec:
        volumes:
          - configMap:
              name: app-config
              items:
              - key: "message"
                path: "greeting.message"
            name: config
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: wildfly-configmap:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 9990
              scheme: HTTP
            initialDelaySeconds: 180
          name: wildfly
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 9990
              scheme: HTTP
            initialDelaySeconds: 10
          securityContext:
            privileged: false
          volumeMounts:
              - name: config
                mountPath: /app/config
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - wildfly
        from:
          kind: ImageStreamTag
          name: wildfly-configmap:latest

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: wildfly-configmap
      group: io.openshift
    name: wildfly-configmap
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: wildfly-configmap
